import Phaser from 'phaser';import {pixelText} from './PixelText';import {positionPanel} from './panelPosition';import {ATLAS,ASSETS,type AssetId} from '../assets/catalog';import type {DialoguePage} from '../home/remoteNpcData';
export class Dialogue {
 isOpen=false;private page=0;private panel:Phaser.GameObjects.Container;private pages:readonly DialoguePage[]=[];private speaker='';private asset:AssetId='remote-cartographer';
 constructor(private scene:Phaser.Scene,private lock:(value:boolean)=>void){this.panel=scene.add.container().setDepth(60).setVisible(false);window.addEventListener('keydown',this.key,true);scene.events.once('shutdown',()=>{window.removeEventListener('keydown',this.key,true);if(this.isOpen)this.close();});}
 open(name:string,asset:AssetId,pages:readonly DialoguePage[]){this.speaker=name;this.asset=asset;this.pages=pages;this.page=0;this.isOpen=true;this.scene.input.keyboard!.resetKeys();this.scene.input.keyboard!.enabled=false;this.lock(true);this.draw();this.scene.events.emit('dialogue-opened',name);}
 close(){this.isOpen=false;this.panel.setVisible(false);this.scene.input.keyboard!.enabled=true;this.scene.input.keyboard!.resetKeys();this.lock(false);}
 private key=(e:KeyboardEvent)=>{if(!this.isOpen)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.code==='Escape')this.close();else if(e.code==='ArrowLeft')this.go(-1);else if(['Enter','Space','KeyE','ArrowRight'].includes(e.code))this.go(1);else if(e.code==='Digit1'&&this.pages[this.page].choices?.[0]){this.choose();}};
 private choose(){const c=this.pages[this.page].choices?.[0];if(!c)return;try{c.action?.();this.page=c.page;this.draw();}catch{this.pages=[{text:'Progress could not be saved. Please try again.'}];this.page=0;this.draw();}}
 private go(step:number){if(step>0&&this.pages[this.page].choices?.[0]?.action){this.choose();return;}if(this.page+step>=this.pages.length){this.close();return;}this.page=Math.max(0,this.page+step);this.draw();}
 update(){if(this.isOpen)positionPanel(this.scene,this.panel,330,146);}
 private draw(){this.panel.removeAll(true);this.panel.setVisible(true);this.panel.add(this.scene.add.zone(0,0,10000,10000).setInteractive());this.panel.add(this.scene.add.graphics().fillStyle(0x233e49,.98).fillRect(-165,-73,330,146).lineStyle(1,0xb08d63).strokeRect(-165,-73,330,146));this.panel.add(this.scene.add.image(-140,-46,ATLAS,ASSETS[this.asset]));
 const text=(x:number,y:number,t:string,color='#dde7e5')=>{const v=pixelText(this.scene,x,y,t,{fontSize:'8px',color});this.panel.add(v);return v;};text(-119,-60,this.speaker,'#f3d49a');text(-150,-22,this.pages[this.page].text);const choice=this.pages[this.page].choices?.[0];if(choice)text(-150,13,'1 · '+choice.label,'#f3d49a').setInteractive().on('pointerdown',()=>{this.choose();});text(-150,43,'← Back','#9dc5cc').setInteractive().on('pointerdown',()=>this.go(-1));text(-54,43,this.page===this.pages.length-1?'Enter · Finish':'Enter · Next','#9dc5cc').setInteractive().on('pointerdown',()=>this.go(1));text(95,43,'Esc · Close','#9dc5cc').setInteractive().on('pointerdown',()=>this.close());this.update();}
}
