import Phaser from 'phaser';import {CoreQuests} from './CoreQuests';import {CORE_QUESTS,type QuestId} from './coreData';import type {DialoguePage} from '../home/remoteNpcData';import {landings} from '../home/Landings';import {banks,ICE_CHUNKS} from '../world/river';import {pixelText} from '../ui/PixelText';import {positionPanel} from '../ui/panelPosition';
export function questPoints(){const forest=landings().find(s=>s.id==='forest')!,beacon=landings().find(s=>s.id==='beacon-rest')!,end=beacon.paths[0].at(-1)!;const b=banks(200);return {survey:[{x:(b[0]+b[1])/2,y:200,r:95},{x:ICE_CHUNKS[1].x+32,y:ICE_CHUNKS[1].y+20,r:115}],weather:[{x:end[0],y:end[1],r:13}],ranger:forest.clearings.slice(1).map(c=>({...c,r:18}))};}
export class CoreQuestView {
 private group:Phaser.GameObjects.Container;private text:Phaser.GameObjects.Text;private hold=0;private notice='';private noticeUntil=0;
 constructor(private scene:Phaser.Scene,readonly core:CoreQuests){this.group=scene.add.container().setDepth(15);this.text=pixelText(scene,-160,-10,'',{fontSize:'8px',color:'#f3d49a',backgroundColor:'#173642',padding:{x:4,y:3}});this.text.setWordWrapWidth(320);this.group.add(this.text);scene.events.on('core-hint',(s:string)=>this.say(s));}
 say(s:string){this.notice=s;this.noticeUntil=this.scene.time.now+4500;this.scene.events.emit('river-cue','ui-open',.25);}
 pages(npc:string):readonly DialoguePage[]|undefined{const id=(Object.keys(CORE_QUESTS) as QuestId[]).find(id=>CORE_QUESTS[id].npc===npc);if(!id)return;const d=CORE_QUESTS[id],state=this.core.status(id);
 if(state==='locked')return [{text:id==='survey'?'Bring your first haul home and sell it.\nThen let us give your next trip a direction.':'There is much to learn along this river.\nFirst, follow the next step in your preparations.'}];
 if(state==='completed')return [{text:id==='ranger'?'Moss has a warm place waiting in the village.\nThank you for giving him a home.':id==='survey'?'Press M for your chart. Next, follow the COAST\nsigns east to Sela at the Coastal Beacon.':id==='weather'?'My readings are yours. Check the village board\nor the River Chart before a long crossing.':'My notes are in your Journal now.\nLook at the habitat and live conditions.'}];
 if(state==='available')return [{text:d.intro,choices:[{label:'I will help.',page:1,action:()=>this.core.start(id)}]},{text:'Your observations will be recorded as you go.\nReturn here when you have finished.'}];
 if(state==='return')return [{text:id==='ranger'?'Both clearings are quiet. Moss trusts your pace.\nWould you give him a warm home in the village?':'You have done the work. Let us put what you\nlearned to use.',choices:[{label:id==='ranger'?'Welcome home, Moss.':'Share what I learned.',page:1,action:()=>this.core.complete(id)}]},{text:d.reward}];
 const q=this.core.state.quests[id]!;return [{text:d.objectives.map((s,i)=>(q.done[i]?'✓ ':'· ')+s).join('\n')+'\nReturn here after your observations.'}];
 }
 update(dt:number,p:{x:number;y:number},walking:boolean,visible:boolean){const points=questPoints();for(const id of ['survey','weather','ranger'] as const){if(!visible||this.core.status(id)!=='active')continue;for(let i=0;i<points[id].length;i++){const point=points[id][i],near=Math.hypot(p.x-point.x,p.y-point.y)<point.r&&(id==='survey'||walking);if(id==='weather'){this.hold=near?this.hold+Math.min(dt,50)/1000:0;if(this.hold>=6)this.core.observe(id,i);}else if(near)this.core.observe(id,i);}}
 const ids=Object.keys(CORE_QUESTS) as QuestId[],active=ids.find(id=>['active','return'].includes(this.core.status(id)));let label='';if(active){const q=this.core.state.quests[active]!;label=q.phase==='return'?`Return to ${CORE_QUESTS[active].npc}`:CORE_QUESTS[active].objectives[q.done.findIndex(d=>!d)];}else if(!this.core.state.sold)label='Bring a catch home and sell your haul';else if(!this.core.has('riverChart'))label='Mara · Follow the western river north to Lookout';else if(!this.core.has('weatherForecast'))label='Visit Sela · Coastal Beacon landing';else if(!this.core.has('corgiCompanion'))label='Meet Iver · Spruce Forest landing';else if(!this.core.has('advancedFishingKnowledge'))label='Visit Eirik · Old Fisher’s Rest';
 if(!active&&this.scene.registry.has('currentGoals'))label='';
 this.text.setText(this.scene.time.now<this.noticeUntil?this.notice:label);this.group.setVisible(visible&&!!this.text.text);positionPanel(this.scene,this.group,330,44);this.group.y=Math.round(this.scene.cameras.main.height/2+(28-this.scene.cameras.main.height/2)/this.scene.cameras.main.zoom);
 }
}
