import {createRegistry} from '../src/game/dev/commands';
import Phaser from 'phaser';import {RiverScene} from '../src/game/scenes/RiverScene';import {CoreQuests} from '../src/game/progression/CoreQuests';import {coreState} from '../src/game/progression/coreData';import {questPoints} from '../src/game/progression/CoreQuestView';import {SaveStore} from '../src/game/player/SaveStore';import {waterAt,waterSpans,WORLD_HEIGHT} from '../src/game/world/river';import {landingWalk,landings} from '../src/game/home/Landings';import {VILLAGE} from '../src/game/home/villageLayout';
const out=document.querySelector('#result')!;out.textContent='';const check=(v:boolean,s:string)=>{out.textContent+=(v?'PASS ':'FAIL ')+s+'\n';if(!v)throw Error(s);};
const state=coreState(undefined),q=new CoreQuests(state,()=>true,()=>{});check(!q.has('riverChart')&&q.status('survey')==='locked','Fresh game starts with basic fishing');q.sale();check(q.status('survey')==='available','First sale introduces survey');q.start('survey');q.observe('survey',0);check(q.status('survey')==='active','Both observations required');q.observe('survey',1);check(q.status('survey')==='return'&&!q.has('riverChart'),'Return before unlock');q.complete('survey');check(q.has('riverChart')&&q.status('weather')==='available','Survey unlocks chart then weather quest');q.start('weather');q.observe('weather',0);q.complete('weather');check(q.has('weatherForecast')&&q.status('ranger')==='available'&&q.status('knowledge')==='available','Forecast opens remaining introductions');q.start('knowledge');q.catch('whitefish');check(q.status('knowledge')==='active','Basic catch not counted');q.catch('char');q.complete('knowledge');check(q.has('advancedFishingKnowledge'),'Single accessible Char earns knowledge');const legacy=coreState(undefined,true);check(legacy.features.length===3&&!legacy.features.includes('corgiCompanion'),'Legacy features grandfathered, dog quest retained');const fail=new CoreQuests(state,()=>false,()=>{});try{fail.start('survey',true);}catch{}check(fail.status('survey')==='locked','Failed save rolls back progression');
const key='qa-core-progression';localStorage.removeItem(key);const store=new SaveStore(key);check(!store.load().core?.features.length,'Fresh save locked');store.write({...store.load(),core:q.state});check(store.load().core?.features.includes('riverChart')===true,'Feature save roundtrip');localStorage.setItem(key,JSON.stringify({version:2,money:50,levels:{},cargo:[],records:{}}));check(store.load().core?.features.length===3&&store.load().money===50,'Old save keeps features and money');localStorage.removeItem(key);
const scene=new RiverScene(null,true);new Phaser.Game({type:Phaser.AUTO,width:900,height:620,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(r=>setTimeout(r,100));scene.scene.pause();const c=scene.core,map=Reflect.get(scene,'map');map.open();check(!map.isOpen,'Real map blocked on fresh game');scene.forecastBoard.open();check(!scene.forecastBoard.isOpen,'Real forecast blocked');c.start('survey',true);const points=questPoints();check(points.survey.every(p=>waterAt(p.x,p.y)),'Survey points on existing water');for(const [id,site] of [['weather','beacon-rest'],['ranger','forest']] as const)check(points[id].every(p=>landingWalk(landings().find(s=>s.id===site)!,p.x,p.y)),'Walkable objectives '+id);
const view=Reflect.get(scene,'coreView');for(const p of points.survey)view.update(50,p,false,true);check(c.status('survey')==='return','Actual survey proximity tracking');c.complete('survey');map.open();check(map.isOpen,'Real M chart unlock');map.close();c.start('weather');for(let i=0;i<122;i++)view.update(50,points.weather[0],true,true);check(c.status('weather')==='return','Six second weather reading');c.complete('weather');scene.forecastBoard.open();check(scene.forecastBoard.isOpen,'Real forecast unlock');scene.forecastBoard.close();c.start('ranger');for(const p of points.ranger)view.update(50,p,true,true);const dog=scene.remoteNpcs.dog.sprite;c.complete('ranger');check(scene.remoteNpcs.dog.sprite===dog&&Math.hypot(dog.x-VILLAGE.corgiHome.x,dog.y-VILLAGE.corgiHome.y)<1,'Same corgi moves to village');check(scene.remoteNpcs.dog.valid(dog.x,dog.y),'Village corgi home valid');let hash=2166136261;for(let y=0;y<WORLD_HEIGHT;y+=2)for(const n of [y,...waterSpans(y).flat()])hash=Math.imul(hash^n,16777619)>>>0;check(hash===153035761,'World geometry unchanged');
for(const p of scene.remoteNpcs.people){const b=document.createElement('button');b.textContent='Talk '+p.data.id;b.onclick=()=>scene.remoteNpcs.dialogue.open(p.data.name,p.data.asset,view.pages(p.data.id));document.querySelector('#buttons')!.append(b);}out.textContent+='ALL CORE CHECKS PASSED';

const registry=createRegistry({core:c,environment:scene.environment,equipment:Reflect.get(scene,'equipment'),cargo:scene.cargo,wallet:Reflect.get(scene,'wallet'),save:()=>true,timeChanged:()=>{},teleport:()=>'',gate:()=>{},spawn:()=>{}});check(registry.execute('/quest-start knowledge').ok,'DEV quest-start');check(registry.execute('/quest-complete knowledge').ok&&c.has('advancedFishingKnowledge'),'DEV quest-complete');check(registry.execute('/quest-reset knowledge').ok&&!c.has('advancedFishingKnowledge'),'DEV quest-reset');check(registry.execute('/unlock-feature riverChart').ok,'DEV feature IDs normalize correctly');check(registry.execute('/lock-feature riverChart').ok&&!c.has('riverChart'),'DEV lock uses actual state');check(!registry.execute('/quest-start nonsense').ok,'DEV invalid quest rejected');
const npc=scene.remoteNpcs.people[0];c.reset('survey');c.sale();scene.remoteNpcs.dialogue.open(npc.data.name,npc.data.asset,view.pages('cartographer'));window.dispatchEvent(new KeyboardEvent('keydown',{code:'Enter'}));check(c.status('survey')==='active','Accept through real dialogue');scene.remoteNpcs.dialogue.close();
