import Phaser from 'phaser';
import {RiverScene} from '../src/game/scenes/RiverScene';
import {SaveStore} from '../src/game/player/SaveStore';
import type {DevConsole} from '../src/game/dev/DevConsole';
import {History} from '../src/game/dev/registry';
const key='arctic-dev-console-check';localStorage.removeItem(key);
const scene=new RiverScene(key,true);new Phaser.Game({type:Phaser.AUTO,width:800,height:600,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});
while(!Reflect.get(scene,'devConsole'))await new Promise(r=>setTimeout(r,100));
const c=Reflect.get(scene,'devConsole') as DevConsole,kayak=Reflect.get(scene,'kayak');
const out=document.querySelector('#result')!,check=(ok:boolean,label:string)=>{out.textContent+=(ok?'PASS ':'FAIL ')+label+'\n';if(!ok)throw Error(label);};
const press=(key:string,code=key)=>{window.dispatchEvent(new KeyboardEvent('keydown',{key,code,bubbles:true,cancelable:true}));window.dispatchEvent(new KeyboardEvent('keyup',{key,code,bubbles:true,cancelable:true}));};
press('/','Slash');check(c.isOpen&&!scene.input.enabled&&scene.physics.world.isPaused,'Slash opens and blocks gameplay');
const input=document.querySelector<HTMLInputElement>('#dev-console input')!;
const execute=(line:string,ok=true)=>{const result=c.registry.execute(line);check(result.ok===ok,line+' → '+result.text);return result;};
const before={x:kayak.x,y:kayak.y};press('w','KeyW');await new Promise(r=>setTimeout(r,150));check(kayak.x===before.x&&kayak.y===before.y,'Movement input stays isolated');
input.value='/set-w';input.dispatchEvent(new Event('input'));press('Tab');check(input.value==='/set-weather','Tab completes command');
input.value='/set-weather hea';input.dispatchEvent(new Event('input'));press('Tab');check(input.value==='/set-weather heavy-snow','Tab completes definition ID');
input.value='/give-money 13';press('Enter');check(scene.wallet.balance===13,'Enter executes real wallet command');press('ArrowUp');check(input.value==='/give-money 13','Up recalls exact command');press('ArrowDown');check(input.value==='/','Down restores draft');
const history=new History();history.add('/give-money 13');history.add('/give-money 13');check(history.entries.length===1,'History avoids consecutive duplicates');
execute('/help');execute('/help give-fish');execute('/help missing',false);execute('/set-wether',false);execute('/set-weather stormy',false);execute('/give-money -1',false);execute('/give-money 1 extra',false);
execute('/set-weather aurora',false);execute('/set-time night');execute('/set-weather aurora');check(scene.environment.phase==='night'&&scene.environment.weather==='aurora','Real night + aurora');execute('/set-weather heavy-snow');
execute('/set-day 3');check(scene.environment.day===3,'Real day advancement');execute('/set-day 1',false);
execute('/give-fish salmon 2');check(scene.cargo.count===2,'Fish definitions and cargo used');execute('/give-fish salmon 20',false);check(scene.cargo.count===2,'Full cargo rejects atomically');
execute('/give-tool lantern');execute('/give-tool rod');check(scene.equipment.levels.lantern===1&&scene.equipment.gear.rod===1,'Tool and rod ownership/equipping');
execute('/give-module icebreaker');execute('/give-module turbo');execute('/give-module cargo');execute('/give-module anchor',false);check(scene.equipment.loadout.filter(Boolean).length===3,'Three-module limit');
execute('/remove-module turbo');execute('/give-module anchor');check(scene.equipment.equipped('anchor')&&!scene.equipment.equipped('turbo'),'Module swap');
execute('/teleport glacier-gorge');check(kayak.y>4000,'World location teleport');execute('/spawn-animal fox');execute('/spawn-animal reindeer',false);
execute('/teleport blueglass',false);execute('/lock-area gorge',false);execute('/unlock-area blueglass');check(scene.equipment.traversalProgress.openedPassages.includes('blueglass-sheet'),'Real gate persistence');execute('/lock-area blueglass');
execute('/save');const saved=new SaveStore(key).load(),environment=new SaveStore(key).loadEnvironment();check(saved.money===13&&saved.cargo.length===2&&saved.levels.lantern===1&&saved.loadout?.includes('anchor')===true&&environment.day===3,'Existing save round-trip preserves changes');
execute('/clear-inventory');check(scene.cargo.count===0&&(scene.cargo.records.salmon??0)>0&&scene.equipment.levels.lantern===1,'Cargo clear retains journal and gear');
press('Escape');check(!c.isOpen&&scene.input.enabled&&!scene.physics.world.isPaused,'Escape restores gameplay');
press('/','Slash');check(c.isOpen,'Console reopens');press('Escape');
localStorage.removeItem(key);out.textContent+='ALL DEV CONSOLE CHECKS PASSED';

const button=document.createElement('button');button.textContent='Inspect console';button.onclick=()=>{c.open();input.value='/set-weather';input.dispatchEvent(new Event('input'));};document.body.prepend(button);
