import Phaser from 'phaser';import {RiverScene} from '../src/game/scenes/RiverScene';
import {Goals,OBJECTIVES,objectiveReward,type GoalContext} from '../src/game/goals/Goals';
const out=document.querySelector('#result')!;const check=(v:boolean,s:string)=>{out.textContent+=(v?'PASS ':'FAIL ')+s+'\n';if(!v)throw Error(s);};
let saved:unknown,rewards=0;const c:GoalContext={now:0,species:[],caught:false,home:false,sold:false,cartographer:false,chart:false,upgraded:false,regions:['starting'],journal:false,forecast:false,capacity:5,count:0};const persist=(s:unknown,r:number)=>{saved=JSON.parse(JSON.stringify(s));rewards+=r;return true;};let g=new Goals(undefined,()=>c,persist,()=>{});
check(g.state.current.length===1&&g.state.current[0].id==='first','Fresh save gives immediate direction; future branches hidden');check(g.state.current[0].reward>0,'Reward visible before completion');
c.caught=true;c.species=['whitefish'];g.event('catch','whitefish');check(g.state.completed.first===0&&rewards===10,'First catch awards money once');check(g.state.current.some(g=>g.id==='wildlife')&&g.state.current.some(g=>g.id==='species'),'Parallel medium and long branches');
c.home=true;c.sold=true;g.event('sale',20);check(g.state.current.some(g=>g.id==='upgrade')&&g.state.current.some(g=>g.id==='cartographer'),'Equipment and NPC branches available together');
c.now=6;g.update();check(g.state.pins.length<=3&&!g.state.pins.includes('first'),'Completed pins clear after brief checkoff');const pin=g.state.pins[0];g.pin(pin);c.now++;g.update();check(!g.state.pins.includes(pin),'Unpin persists without automatic re-pin');g.pin(pin);check(g.state.pins.includes(pin),'Pin works');g.collapse();check(g.state.collapsed,'Collapse works');const earned=rewards;g=new Goals(saved,()=>c,persist,()=>{});check(rewards===earned&&g.state.pins.includes(pin),'Reload preserves pins and cannot duplicate rewards');
c.chart=true;c.cartographer=true;c.upgraded=true;c.species=Array.from({length:20},(_,i)=>String(i));c.regions=['starting','bend','lake','gorge','estuary'];c.landings=['a','b','c','d','e','f','g'];c.landmarks=['a','b','c'];c.modules=3;c.trophies=1;c.npcs=['cartographer','weatherObserver','ranger','oldFisher'];c.now=10;g.update();check(g.state.completed['twenty-species']!==undefined&&g.state.completed['all-landings']!==undefined&&g.state.completed.everyone!==undefined,'Advanced facts count across long-term milestones');
for(let i=0;i<8;i++)g.event('observe',String(i));check(g.state.completed.wildlife!==undefined,'Unique wildlife observation persists');const money=rewards;g=new Goals(saved,()=>c,persist,()=>{});check(rewards===money,'Advanced reload does not pay twice');const rewardSet=new Set(OBJECTIVES.map(objectiveReward));check(rewardSet.size>=8&&objectiveReward(OBJECTIVES.find(d=>d.id==='twenty-species')!)>objectiveReward(OBJECTIVES[0]),'Central rewards scale with effort, stage and rarity');
const legacy=new Goals({version:1,current:[],starters:['first','home','sale'],collapsed:true},()=>({...c,caught:true,species:['whitefish'],chart:false,upgraded:false,regions:['starting'],landings:[],landmarks:[],modules:0,trophies:0,npcs:[]}),()=>true,()=>{});check(legacy.state.completed.first===0&&legacy.state.collapsed,'Legacy starter completion migrated');
const fail=new Goals(saved,()=>c,()=>false,()=>{}),before=JSON.stringify(fail.state);fail.collapse();check(JSON.stringify(fail.state)===before,'Failed save rolls back');const beforeReset=rewards;g.dev('reset');check(rewards===beforeReset,'DEV refresh cannot farm completed rewards');
const scene=new RiverScene(null,true);new Phaser.Game({type:Phaser.AUTO,width:900,height:620,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(r=>setTimeout(r,100));scene.scene.pause();const view=Reflect.get(scene,'goalsView');view.update(true);const wallet=Reflect.get(scene,'wallet'),balance=wallet.balance;scene.cargo.createCatch('char');scene.goals.event('catch','char');check(wallet.balance===balance+10,'Real fish record rewards the real wallet');scene.goals.event('catch','char');check(wallet.balance===balance+10,'Real wallet cannot receive duplicate reward');view.update(true);
const button=(label:string,fn:()=>void)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;document.body.insertBefore(b,document.querySelector('#test'));};button('Objectives',()=>{view.update(true);view.open();});button('Close',()=>view.close());button('Advanced view',()=>{for(const d of ['home','sale','cartographer','chart','upgrade','species'])scene.goals.dev('complete',d);view.update(true);view.open();});check(scene.goals.state.pins.length<=3,'Real HUD limited to three pins');
view.update(true);window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyO',bubbles:true}));check(view.isOpen&&!scene.input.keyboard!.enabled,'O opens screen and disables gameplay keyboard');window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyI',bubbles:true}));check(!Reflect.get(scene,'tools').isEditing,'Inventory shortcut cannot open behind Objectives');window.dispatchEvent(new KeyboardEvent('keydown',{code:'Escape',bubbles:true}));check(!view.isOpen&&scene.input.keyboard!.enabled,'Escape closes and restores keyboard');
const idsBefore=Object.keys(g.state.completed).sort().join(',');c.now+=86400;g.update();check(Object.keys(g.state.completed).sort().join(',')===idsBefore,'Day advancement never resets objectives');
button('Long-term',()=>{view.update(true);view.open();Reflect.set(view,'tab','LONG-TERM');Reflect.set(view,'page',0);Reflect.get(view,'draw').call(view);});button('Completed',()=>{view.update(true);view.open();Reflect.set(view,'tab','COMPLETED');Reflect.set(view,'page',0);Reflect.get(view,'draw').call(view);});button('Small viewport',()=>{scene.scale.resize(640,360);view.update(true);view.open();});
const {SaveStore}=await import('../src/game/player/SaveStore');const key='qa-objectives-'+Date.now(),store=new SaveStore(key);try{const daily={day:7,requests:['separate-board']};store.write({...store.load(),goals:g.state,money:rewards,daily});const loaded=store.load();let paid=0;new Goals(loaded.goals,()=>c,(state,reward)=>{paid+=reward;return store.write({...store.load(),goals:state,money:store.load().money+reward});},()=>{});check(paid===0&&store.load().money===rewards,'Real SaveStore reload preserves rewards');check(JSON.stringify(store.load().daily)===JSON.stringify(daily),'Objective saves preserve separate daily request data');}finally{localStorage.removeItem(key);}
view.close();view.update(true);const objectiveButton=document.getElementById('objectives-button')!;const visibleActive=scene.goals.state.current.filter(g=>g.completeAt===undefined&&g.scope!=='long').length;check(objectiveButton.getAttribute('aria-label')===`Objectives (${visibleActive})`,'HUD count matches only Active-tab objectives');Reflect.set(view,'tab','LONG-TERM');objectiveButton.click();check(view.isOpen&&Reflect.get(view,'tab')==='ACTIVE'&&Reflect.get(view,'list').call(view).length===visibleActive,'Actual HUD click opens matching Active list');view.close();
