import Phaser from 'phaser';
import {RiverScene} from '../src/game/scenes/RiverScene';
import {SaveStore} from '../src/game/player/SaveStore';
import {Cargo} from '../src/game/player/Cargo';
import {Equipment} from '../src/game/upgrades/Equipment';
import {Wallet} from '../src/game/player/Wallet';
import {STARTER_LEVELS,RODS,MODULE_IDS,shopUpgrades,moduleLoadout,type ModuleId} from '../src/game/upgrades/data';
import {WORKSHOP_BAY} from '../src/game/home/villageLayout';
const out=document.querySelector('#result')!,check=(ok:boolean,s:string)=>{out.textContent+='\n'+(ok?'PASS ':'FAIL ')+s;if(!ok)throw Error(s);};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms)),key=(code:number,down:boolean)=>window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{keyCode:code,which:code,bubbles:true}));
const tap=async(code:number)=>{key(code,true);await wait(85);key(code,false);await wait(140);};
const saveKey='arctic-drift.check-items',store=new SaveStore(saveKey);
const oldLevels={...STARTER_LEVELS,rod:1,line:3,reel:2,cargo:2,lantern:1,finder:1,icebreaker:1};
const oldCargo=new Cargo(12);for(let i=0;i<9;i++)oldCargo.add('whitefish',0,()=>.4);
localStorage.setItem(saveKey,JSON.stringify({version:2,money:317,levels:oldLevels,loadout:['cargo','lantern','finder'],cargo:oldCargo.entries,records:oldCargo.records,openedPassages:['ice-cut-sheet']}));
const old=store.load(),migrated=new Equipment(new Cargo(12,old.cargo),new Wallet(old.money),store,old.levels,old.loadout);
check(old.levels.rod===3&&old.levels.line===0&&old.levels.reel===0,'Legacy components consolidate into strongest complete rod');
check(old.cargo.length===9&&old.money===317&&old.openedPassages?.[0]==='ice-cut-sheet','Cargo, money, records and permanent traversal preserved');
check(migrated.gear.rod===3&&migrated.value('line')===1.65&&migrated.value('reel')===.54,'Migrated rod supplies all three effects without stacking old components');
check(migrated.value('lantern')>0&&migrated.value('finder')>0&&migrated.loadout.join(',')==='cargo,,','Lantern and finder become personal gear and free their former slots');
migrated.save();check(store.load().levels.rod===3,'Migration survives repeated load without reroll or duplicate credit');
check(moduleLoadout(['turbo','turbo','finder'],{...STARTER_LEVELS,turbo:1}).join(',')==='turbo,,','Loadouts reject duplicates and personal gear');
check(!shopUpgrades('tools').includes('line')&&!shopUpgrades('tools').includes('reel')&&shopUpgrades('tools').includes('lantern')&&MODULE_IDS.length===9,'Only two active catalogs; no component tracks or personal modules');
localStorage.removeItem(saveKey);store.write({...store.load(),money:4500});
const scene=new RiverScene(saveKey,true),game=new Phaser.Game({type:Phaser.AUTO,width:800,height:650,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});
while(!scene.fishing)await wait(100);game.events.off(Phaser.Core.Events.BLUR);
const home=Reflect.get(scene,'home'),kayak=Reflect.get(scene,'kayak'),body=kayak.body as Phaser.Physics.Arcade.Body,e=scene.equipment,panel=scene.harborPanel;
const select=(i:number)=>{Reflect.set(panel,'selection',i);Reflect.get(panel,'refresh').call(panel);};
const chooseModule=(id:ModuleId)=>select(shopUpgrades('gear').indexOf(id));
// Use the existing NPC interaction and keyboard purchase path.
home.walking=true;home.fisherman.setVisible(true).setPosition(349,1206);kayak.setOccupied(false);home.setMovementEnabled(true);await wait(80);await tap(69);
check(panel.isOpen&&panel.tab==='tools','Edda opens Player Gear on foot');
const start=scene.wallet.balance,base=e.fightFor('salmon');
for(let model=1;model<=3;model++){select(model);await tap(69);check(e.levels.rod===model&&e.gear.rod===model,'Buy and equip '+RODS[model].name);}
check(scene.wallet.balance===start-660,'Named rod prices charge exactly once');
const best=e.fightFor('salmon');check(best.safeTensionWidth>base.safeTensionWidth&&best.snapTolerance>base.snapTolerance&&best.progressRequired<base.progressRequired,'Equipped rod changes the actual next fish fight');
select(0);await tap(69);check(e.gear.rod===0&&e.fightFor('salmon').safeTensionWidth===base.safeTensionWidth&&e.levels.rod===3,'Equip Basic Rod without losing owned higher rods');select(3);await tap(69);
const items=Reflect.get(panel,'gearItems') as {id:string}[];
for(const id of ['lantern','finder']){select(items.findIndex(i=>i.id===id));await tap(69);check(e.value(id as 'lantern'|'finder')>0,'Buy personal '+id+' without a module slot');}
check(e.loadout.every(id=>id===null),'Personal gear never consumes slots');
await tap(69);check(e.gear.selectedTool==='finder','Owned finder selects for active use');await tap(69);check(e.value('finder')>0,'Finder ownership remains available');
await tap(27);check(!panel.isOpen,'Escape restores walking');
home.walking=false;home.fisherman.setVisible(false);kayak.setOccupied(true);home.setMovementEnabled(true);body.reset(625,WORKSHOP_BAY.y);key(65,true);
for(let i=0;i<50&&kayak.x>571;i++)await wait(40);key(65,false);await wait(800);await tap(69);
check(panel.isOpen&&panel.tab==='gear'&&!home.walking,'Paddle into service bay and open workshop with E');
for(const id of ['cargo','turbo','hull','icebreaker','speed'] as const){chooseModule(id);await tap(69);check(e.levels[id]===1,'Own '+id);}
e.setSlot(0,'cargo');e.setSlot(1,'turbo');e.setSlot(2,'hull');await wait(50);
check(scene.cargo.capacity===8&&e.loadout.filter(Boolean).length===3,'Three module slots activate storage, motor and hull');
const layers=Reflect.get(kayak,'attachments') as Map<string,Phaser.GameObjects.Image>;
for(const angle of [0,.8,1.57,3.14,-1.57]){kayak.setRotation(angle);await wait(30);check([...layers.values()].filter(i=>i.visible).length===3&&[...layers.values()].filter(i=>i.visible).every(i=>i.x===kayak.x&&i.y===kayak.y&&Math.abs(i.rotation-kayak.rotation)<.001),'Installed attachments align at '+angle);}
for(let i=0;i<6;i++)scene.cargo.add('whitefish');check(e.setSlot(0,null)==='cargo-full'&&scene.cargo.count===6,'Storage removal cannot destroy excess cargo');
e.setSlot(2,'icebreaker');check(e.value('icebreaker')===1&&!layers.get('hull')?.visible,'Bow replacement activates traversal and removes hull art');
e.setSlot(2,'hull');chooseModule('cargo');await tap(66);check(scene.cargo.capacity===12,'Named storage model upgrades installed capacity');
await tap(27);
const oldValue=kayak.moduleValue;key(68,true);kayak.waterFlow={x:0,y:0,speed:1};
const recoverySpeed=(hull:number)=>{body.reset(630,1510);kayak.moduleValue=(id:string)=>id==='hull'?hull:0;kayak.collisionRecovery();kayak.update(0,50);return body.velocity.length();};
const unbraced=recoverySpeed(0),braced=recoverySpeed(1);key(68,false);kayak.moduleValue=oldValue;
check(braced>unbraced*1.5,'Reinforced Hull gives visibly quicker acceleration out of a collision');
body.reset(630,1510);kayak.waterFlow={x:0,y:0,speed:1};
key(83,true);await wait(650);const normal=body.velocity.length();key(16,true);await wait(800);
out.textContent+='\nBOOST '+JSON.stringify({normal,speed:body.velocity.length(),boosting:kayak.boosting,energy:kayak.boostEnergy,x:kayak.x,y:kayak.y});
check(kayak.boosting&&body.velocity.length()>normal*1.3&&kayak.boostEnergy<.9,'Physical Shift key gives faster travel and spends motor energy');
await wait(2500);check(!kayak.boosting&&kayak.boostEnergy===0,'Held Shift exhausts motor rather than boosting forever');
key(16,false);key(83,false);await wait(2000);check(kayak.boostEnergy>.2,'Releasing Shift recharges');
const loadout=e.loadout;check(e.setSlot(1,null)==='workshop-only'&&JSON.stringify(e.loadout)===JSON.stringify(loadout),'Loadout cannot change away from workshop');
body.reset(WORKSHOP_BAY.x,WORKSHOP_BAY.y);e.setSlot(1,null);key(83,true);key(16,true);await wait(200);check(!kayak.boosting,'Uninstalled motor cannot boost');key(83,false);key(16,false);body.reset(WORKSHOP_BAY.x,WORKSHOP_BAY.y);e.setSlot(1,'turbo');e.save();
const reloaded=new RiverScene(saveKey,true);check(reloaded.equipment.gear.rod===3&&reloaded.equipment.value('finder')>0&&reloaded.equipment.loadout.join(',')==='cargo,turbo,hull'&&reloaded.cargo.count===6&&reloaded.cargo.capacity===12,'Save restores rod, personal gear, three slots and cargo');
body.reset(WORKSHOP_BAY.x,WORKSHOP_BAY.y);scene.cameras.main.stopFollow();scene.cameras.main.centerOn(WORKSHOP_BAY.x,WORKSHOP_BAY.y);panel.open('gear');chooseModule('turbo');
out.textContent+='\nALL ITEM CHECKS PASSED';
