import {sceneryFootprints} from '../src/game/world/sceneryCollision';
import {VILLAGE} from '../src/game/home/villageLayout';
import Phaser from 'phaser';import {RiverScene} from '../src/game/scenes/RiverScene';import {navigationLandmarks,landDecorationFits,waterAt,WORLD_WIDTH,WORLD_HEIGHT} from '../src/game/world/river';import {NAVIGATION_LANDMARKS} from '../src/game/world/navigationIdentity';import {Discovery,MAP_MARKERS} from '../src/game/map/discovery';
const scene=new RiverScene(null,true);new Phaser.Game({type:Phaser.AUTO,width:900,height:620,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(r=>setTimeout(r,100));scene.scene.pause();const out=document.querySelector('#result')!;out.textContent='';const check=(v:boolean,s:string)=>{out.textContent+=(v?'PASS ':'FAIL ')+s+'\n';if(!v)throw Error(s);};
check(navigationLandmarks().length===NAVIGATION_LANDMARKS.length,'All nine authored wayfinding landmarks fit');for(const c of navigationLandmarks()){const authored=NAVIGATION_LANDMARKS.find(p=>p.id===c.id)!;check(Math.hypot(c.x+c.width/2-authored.x,c.y+c.height/2-authored.y)<320,'Visible from local route '+c.name);check(sceneryFootprints.some(p=>p.asset===c.asset&&Math.abs(p.x-c.x-c.width/2)<1&&Math.abs(p.y-c.y)<c.height),'Landmark artwork and physical footprint '+c.name);check(landDecorationFits(c.x,c.y,c.width,c.height),'Dry physical footprint '+c.name);check(MAP_MARKERS.filter(m=>m.id===c.id).length===1,'Single stable marker '+c.id);}
const homeDiscovery=new Discovery();check(homeDiscovery.visit(VILLAGE.square.x,VILLAGE.square.y).found.some(m=>m.id==='starting'),'Village walking belongs to home region');
const d=new Discovery();const entry=d.visit(3400,2800);check(entry.found.some(m=>m.id==='estuary'),'Region discovery works from lateral approach');check(!d.visit(3400,2800).found.some(m=>m.id==='estuary'),'No repeating region message');check(!new Discovery(d.snapshot()).visit(3400,2800).found.some(m=>m.id==='estuary'),'First-entry state persists');check(!d.known(265,2080)&&!d.landmarks.has('lantern-hollow'),'Secret cave remains hidden');check(new Discovery({landmarks:['lake'],regions:[]}).visitedAreas.has('lake'),'Legacy known area migrates');
for(const c of navigationLandmarks()){const b=document.createElement('button');b.textContent=c.name;b.onclick=()=>{out.textContent+='\nVIEW '+c.name+' '+c.x+','+c.y;scene.cameras.main.stopFollow();scene.cameras.main.setZoom(1);scene.cameras.main.centerOn(c.x+c.width/2,c.y+c.height/2);};document.querySelector('#buttons')!.append(b);}
const b=document.createElement('button');b.textContent='Chart review';b.onclick=()=>{const map=Reflect.get(scene,'map');for(let y=100;y<WORLD_HEIGHT;y+=90)for(let x=100;x<WORLD_WIDTH;x+=90)if(waterAt(x,y))map.discovery.visit(x,y);map.open();};document.querySelector('#buttons')!.append(b);out.textContent+='ALL IDENTITY CHECKS PASSED';
