import Phaser from 'phaser';import {RiverScene} from '../src/game/scenes/RiverScene';import {waterAt,waterSpans,WORLD_WIDTH,WORLD_HEIGHT} from '../src/game/world/river';import {VILLAGE,canWalk} from '../src/game/home/villageLayout';import {NETWORK_ROUTES,WORLD_REVISION,REGION_CORES} from '../src/game/world/regionNetwork';import {areaAt} from '../src/game/world/spawnRules';import {Discovery} from '../src/game/map/discovery';import {landings,landingWalk} from '../src/game/home/Landings';
const scene=new RiverScene(null,true);new Phaser.Game({type:Phaser.AUTO,width:900,height:650,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(r=>setTimeout(r,100));scene.scene.pause();
const out=document.querySelector('#result')!;out.textContent='';const check=(ok:boolean,name:string)=>{out.textContent+=(ok?'PASS ':'FAIL ')+name+'\n';if(!ok)throw Error(name);};
check(WORLD_WIDTH/WORLD_HEIGHT>.7,'World now spans both axes');check(VILLAGE.square.x>WORLD_WIDTH*.25&&VILLAGE.square.x<WORLD_WIDTH*.75,'Village centrally located');
const h=Reflect.get(scene,'home'),k=Reflect.get(scene,'kayak');k.body.reset(VILLAGE.dock.x,VILLAGE.dock.y);k.setVelocity(0,0);check(h.interactDock()&&h.walking,'Relocated village landing');check(h.interactDock()&&!h.walking,'Relocated village boarding');
// Flood only hull-clear water: center plus perimeter samples, rather than point connectivity.
const step=10,cols=Math.ceil(WORLD_WIDTH/step),rows=Math.ceil(WORLD_HEIGHT/step),valid=new Uint8Array(cols*rows),seen=new Uint8Array(cols*rows);
for(let iy=0;iy<rows;iy++)for(let ix=0;ix<cols;ix++){const x=ix*step,y=iy*step;valid[iy*cols+ix]=Number(Array.from({length:8},(_,n)=>n*Math.PI/4).every(a=>waterAt(x+Math.cos(a)*17,y+Math.sin(a)*17)));}
const startX=Math.round(VILLAGE.dock.x/step),startY=Math.round(VILLAGE.dock.y/step),queue=[startY*cols+startX];seen[queue[0]]=1;
for(let cursor=0;cursor<queue.length;cursor++){const i=queue[cursor],x=i%cols,y=Math.floor(i/cols);for(const [nx,ny]of[[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const j=ny*cols+nx;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&valid[j]&&!seen[j]){seen[j]=1;queue.push(j);}}}
const reachable=(x:number,y:number)=>Array.from({length:9},(_,i)=>{const nx=Math.round(x/step)+(i%3)-1,ny=Math.round(y/step)+Math.floor(i/3)-1;return seen[ny*cols+nx];}).some(Boolean);
for(const p of [{id:'starting',x:850,y:1600},{id:'bend',x:850,y:2200},{id:'lake',x:850,y:3650},{id:'gorge',x:800,y:4900},{id:'estuary',x:3400,y:2800}])check(reachable(p.x,p.y),'Hull-clear route to '+p.id);
for(const [id,p]of Object.entries(REGION_CORES))check(reachable(p.x,p.y),'Expanded regional core '+id);
for(const s of landings()){check(reachable(s.x,s.y),'Reachable '+s.name);for(const path of s.paths)for(const [x,y]of path)check(landingWalk(s,x,y),'Walk endpoint '+s.id);}
check(areaAt(2800,3400)==='estuary'&&areaAt(2716,VILLAGE.dock.x)==='starting','Spatial region identities');
const migrated=new Discovery({regions:['3,9','6,28'],landmarks:['village','seller','lake','old-dock']});check(migrated.landmarks.has('lake')&&migrated.known(VILLAGE.npcs.seller.x,VILLAGE.npcs.seller.y),'Stable ID discovery migration');check(migrated.snapshot().worldRevision===WORLD_REVISION,'Map migration versioned');
const revisionTwo=new Discovery({worldRevision:2,regions:['3,9'],landmarks:['lake'],visitedAreas:['lake']});check(revisionTwo.regions.has('3,9')&&revisionTwo.visitedAreas.has('lake'),'Revision 2 exploration survives contour migration');
// Closed sheets must cut the only approach; inflate each sheet by the kayak radius.
const {ICE_PASSAGES,passageBounds}=await import('../src/game/world/traversalData');const {SIDE_ROUTES}=await import('../src/game/world/sideRoutes');
const blocked=(x:number,y:number)=>ICE_PASSAGES.some(p=>{const b=passageBounds(p);return x>b.x-17&&x<b.x+b.width+17&&y>b.y-17&&y<b.y+b.height+17;});
const closed=new Uint8Array(valid.length),cq=[queue[0]];closed[cq[0]]=1;
for(let c=0;c<cq.length;c++){const i=cq[c],x=i%cols,y=Math.floor(i/cols);for(const [nx,ny]of[[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const j=ny*cols+nx;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&valid[j]&&!closed[j]&&!blocked(nx*step,ny*step)){closed[j]=1;cq.push(j);}}}
for(const p of ICE_PASSAGES){const r=SIDE_ROUTES.find(r=>r.id===p.route)!;check(!closed[Math.round(r.pocket.y/step)*cols+Math.round(r.pocket.x/step)],'Gate cannot be bypassed: '+p.route);check(reachable(r.pocket.x,r.pocket.y),'Opened pocket reachable: '+p.route);}
const {DynamicWorld}=await import('../src/game/world/DynamicWorld');const {restoreSchool}=await import('../src/game/fishing/schools');
const signatures=new Set<string>();for(let day=1;day<=5;day++){const w=new DynamicWorld(day);w.newDay(day,{x:3400,y:2800},{left:3350,top:2750,right:3450,bottom:2850});check(w.spots.some(s=>s.area==='estuary'),'Estuary activity day '+day);check(w.spots.every(s=>waterAt(s.x,s.y)&&areaAt(s.y,s.x)===s.area),'Valid spatial spawning day '+day);signatures.add(JSON.stringify(w.spots.map(s=>[s.x,s.y])));const restored=new DynamicWorld();check(restored.restore(w.snapshot())&&restored.spots.length===w.spots.length,'Dynamic save roundtrip '+day);check(w.spots.every(s=>!s.school||!!restoreSchool(s.school)),'All schools survive wider coordinates');}check(signatures.size===5,'Trips remain randomized');
const fingerprint=JSON.stringify(Array.from({length:100},(_,i)=>waterSpans(i*50)));Reflect.get(scene,'dynamicWorld').newDay(818,k,scene.cameras.main.worldView);check(fingerprint===JSON.stringify(Array.from({length:100},(_,i)=>waterSpans(i*50))),'Daily state cannot change geography');

for(const p of [{id:'Village',x:VILLAGE.square.x,y:VILLAGE.square.y},...NETWORK_ROUTES.map(r=>({id:r.name,x:r.points[Math.floor(r.points.length/2)][0],y:r.points[Math.floor(r.points.length/2)][1]}))]){const b=document.createElement('button');b.textContent=p.id;b.onclick=()=>{scene.cameras.main.stopFollow();scene.cameras.main.setZoom(1);scene.cameras.main.centerOn(p.x,p.y);};document.querySelector('#buttons')!.append(b);}

const cb=document.createElement('button');cb.textContent='Chart';cb.onclick=()=>{const map=Reflect.get(scene,'map');for(let y=120;y<WORLD_HEIGHT;y+=90)for(let x=100;x<WORLD_WIDTH;x+=90)if(waterAt(x,y))map.discovery.visit(x,y);map.open();};document.querySelector('#buttons')!.append(cb);
const {SaveStore}=await import('../src/game/player/SaveStore');const key='arctic-test-region-migration';const store=new SaveStore(key);try{const old=store.load();old.money=234;old.levels.cargo=1;old.loadout=['cargo',null,null];old.openedPassages=['ice-cut-sheet'];store.write(old);store.writeMap({regions:['3,9','6,28'],landmarks:['village','lake']});const d=new Discovery(store.loadMap());store.writeMap(d.snapshot());const loaded=store.load();check(loaded.money===234&&loaded.levels.cargo===1&&loaded.loadout?.[0]==='cargo'&&loaded.openedPassages?.includes('ice-cut-sheet')===true,'Save migration retains economy, equipment and opened gates');check(new Discovery(store.loadMap()).landmarks.has('lake'),'Migrated discovery survives another reload');}finally{localStorage.removeItem(key);}

out.textContent+='\nALL NETWORK CHECKS PASSED';
