import Phaser from 'phaser';
import {Discovery,MAP_MARKERS} from '../src/game/map/discovery';
import {AREA_SPAWNS,type AreaId} from '../src/game/world/spawnRules';
import {SaveStore} from '../src/game/player/SaveStore';
import {RiverScene} from '../src/game/scenes/RiverScene';
import {createRegistry} from '../src/game/dev/commands';
const out=document.querySelector('#result')!;function check(v:boolean,s:string){out.textContent+=(v?'PASS ':'FAIL ')+s+'\n';if(!v)throw Error(s);}
const d=new Discovery(),r=d.regional;
for(const region of Object.keys(AREA_SPAWNS) as AreaId[]){check(r.chartLines(region).length===0,'Unvisited region hidden: '+region);r.dev('discover',region);const before=r.summary(region).percent;r.dev('complete',region);check(r.summary(region).percent===100,'100% without RNG or secret requirements: '+region);check(r.fishSpeciesCaughtInRegion(region).length===0,'DEV completion invents no fish: '+region);r.dev('reset',region);check(r.summary(region).percent===0,'Regional reset: '+region);}
r.dev('discover','starting');const pct=r.summary('starting').percent;r.recordFish('starting','whitefish');r.recordFish('starting','whitefish');r.recordFish('lake','whitefish');check(r.fishSpeciesCaughtInRegion('starting').length===1&&r.fishSpeciesCaughtInRegion('lake').length===1,'Same species independently recorded per region, never duplicated');r.observeWildlife('starting','bird');r.observeWildlife('starting','bird');check(r.wildlifeSpeciesObservedInRegion('starting').length===1,'Repeated encounters do not inflate counts');check(r.summary('starting').percent===pct,'Ecology cannot obstruct exploration completion');
const cave=r.catalog.find(p=>p.category==='caves')!,m=MAP_MARKERS.find(m=>m.id===cave.id)!;r.dev('discover',cave.region);check(!r.chartLines(cave.region).join().includes('Caves'),'Hidden caves have no missing counts');d.visit(m.x,m.y);check(r.cavesDiscovered(cave.region).includes(cave.id),'Actual location discovery reused');check(r.chartLines(cave.region).some(s=>s.includes('Caves'))&&!r.chartLines(cave.region).join().includes(m.name),'Known cave count without secret locations');
const reloaded=new Discovery(d.snapshot());check(JSON.stringify(reloaded.regional.snapshot())===JSON.stringify(r.snapshot()),'Reload preserves biological provenance');check(reloaded.regional.cavesDiscovered(cave.region).includes(cave.id),'Stable landmark IDs survive reload');
const legacy=new Discovery({visitedAreas:['gorge','lake'],landmarks:[cave.id],regions:[]});legacy.regional.inferLegacy({huchen:10,salmon:3},['musk-ox','owl']);check(legacy.regional.fishSpeciesCaughtInRegion('gorge').includes('huchen'),'Unique-region old fish inferred');check(!legacy.regional.fishSpeciesCaughtInRegion('lake').includes('salmon'),'Shared fish provenance is not guessed');check(legacy.regional.wildlifeSpeciesObservedInRegion('lake').includes('musk-ox'),'Unambiguous old wildlife inferred');
r.onChange=()=>false;const snap=JSON.stringify(d.snapshot());r.observeWildlife('starting','hare');check(JSON.stringify(d.snapshot())===snap,'Failed save rolls back');r.onChange=()=>true;
const key='qa-regions-'+Date.now(),store=new SaveStore(key);try{store.writeMap(d.snapshot());check(new Discovery(store.loadMap()).regional.fishSpeciesCaughtInRegion('starting').includes('whitefish'),'SaveStore regional round trip');}finally{localStorage.removeItem(key);}
const scene=new RiverScene(null,true);new Phaser.Game({type:Phaser.AUTO,width:800,height:600,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(resolve=>setTimeout(resolve,100));scene.scene.pause();const map=Reflect.get(scene,'map');const fish=scene.cargo.createCatch('char');scene.events.emit('fish-landed',{fish,area:'starting',conditions:scene.environment.conditions,large:false});check(map.discovery.regional.fishSpeciesCaughtInRegion('starting').includes('char')&&!!scene.cargo.records.char,'Real catch event agrees with Journal');scene.events.emit('wildlife-observed','bird',2500,1440);check(map.discovery.regional.wildlifeSpeciesObservedInRegion('starting').includes('bird'),'Real wildlife event uses encounter region');
const registry=createRegistry({regional:map.discovery.regional,environment:scene.environment,equipment:Reflect.get(scene,'equipment'),cargo:scene.cargo,wallet:Reflect.get(scene,'wallet'),save:()=>true,timeChanged:()=>{},teleport:()=>'',gate:()=>{},spawn:()=>{}});for(const cmd of ['region-discover lake','region-progress lake','region-complete lake','region-reset lake'])check(registry.execute('/'+cmd).ok,'DEV '+cmd);check(!registry.execute('/region-progress nowhere').ok,'Invalid region rejected');
scene.core.setFeature('riverChart',true);
for(const region of Object.keys(AREA_SPAWNS) as AreaId[]){const b=document.createElement('button');b.textContent=AREA_SPAWNS[region].name;b.onclick=()=>{map.discovery.regional.dev('complete',region);map.open();Reflect.set(map,'selected',region);const marker=MAP_MARKERS.find(m=>m.id===region)!;Reflect.get(map,'center').call(map,marker.y,marker.x);};document.querySelector('#buttons')!.append(b);}

map.open();check(Reflect.get(map,'selected')==='starting','Opening Chart automatically selects current region');check(Reflect.get(map,'list').list.some((item:any)=>typeof item.text==='string'&&item.text.includes('Explored')),'Exploration summary visible immediately on open');
