import Phaser from 'phaser';
import { RiverScene } from '../src/game/scenes/RiverScene';
import { Home } from '../src/game/home/Home';
import { Kayak } from '../src/game/entities/Kayak';
import { VILLAGE, canWalk } from '../src/game/home/villageLayout';
import { SLEEP } from '../src/game/home/Sleep';
import { SaveStore } from '../src/game/player/SaveStore';
const keyName='arctic-drift.check-sleep',store=new SaveStore(keyName);
const results:string[]=[];
const check=(ok:boolean,text:string)=>{results.push(`${ok?'PASS':'FAIL'} ${text}`);document.querySelector('#result')!.textContent=results.join('\n');if(!ok)throw Error(text);};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const key=(code:number,down:boolean)=>window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{keyCode:code,which:code,bubbles:true}));
const press=async(code=69)=>{key(code,true);await wait(60);key(code,false);};
const scene=new RiverScene(keyName,true),game=new Phaser.Game({type:Phaser.AUTO,parent:'test',width:1000,height:640,pixelArt:true,physics:{default:'arcade'},scene:[scene]});
try{
 while(!Reflect.get(scene,'home'))await wait(100);
 await wait(100);
 const home=Reflect.get(scene,'home') as Home,kayak=scene.children.list.find(c=>c instanceof Kayak) as Kayak;
 Object.assign(scene.environment,{state:{elapsed:550,weather:'aurora',remaining:160,seed:79}});
 check(!scene.sleep.begin(),'Cannot sleep from kayak');
 (kayak.body as Phaser.Physics.Arcade.Body).reset(VILLAGE.dock.x,VILLAGE.dock.y);home.interactDock();
 check(!scene.sleep.begin(),'Cannot sleep away from igloo');
 home.fisherman.setPosition(SLEEP.outside.x,SLEEP.outside.y);
 check(canWalk(SLEEP.outside.x,SLEEP.outside.y,Reflect.get(home.fisherman,'obstacles')),'Igloo approach and morning exit are walkable');
 Object.assign(scene.environment,{state:{elapsed:200,weather:'clear',remaining:160,seed:79}});
 check(!scene.sleep.begin(),'Daytime sleep is unavailable');
 Object.assign(scene.environment,{state:{elapsed:550,weather:'aurora',remaining:160,seed:79}});
 scene.cargo.unload();scene.cargo.add('salmon',0,()=>.5);scene.cargo.add('char',0,()=>.6);scene.wallet.credit(127);scene.equipment.levels.rod=1;scene.equipment.save();
 const before=JSON.stringify(store.load()),trip=scene.dynamicWorld.trip;
 await press();check(scene.sleep.active,'E begins sleep at existing igloo');
 await wait(350);check(scene.environment.phase==='night'&&scene.sleep.active,'Sleep is a gradual transition, not an instant time change');
 const x=home.fisherman.x;key(68,true);await wait(700);key(68,false);
 check(home.fisherman.x<=x,'Normal walking input is disabled during entry');
 check(home.lighting.homeWarmth===1,'Igloo receives warm sleep lighting');
 await wait(2500);
 for(let i=0;i<80&&scene.sleep.active;i++)await wait(100);
 check(!scene.sleep.active&&scene.environment.phase==='morning','Full sleep completes in morning');
 check(scene.environment.weather!=='aurora','Night-only weather clears at dawn');
 check(scene.dynamicWorld.trip===trip+1&&scene.dynamicWorld.spots.length>0,'Fresh dynamic fishing/wildlife state is generated');
 check(JSON.stringify(store.load())===before,'Money, cargo, upgrades and records are unchanged');
 check(store.loadEnvironment().elapsed===30,'Morning is persisted by existing save system');
 check(home.fisherman.visible&&Math.hypot(home.fisherman.x-SLEEP.outside.x,home.fisherman.y-SLEEP.outside.y)<1,'Player returns outside original igloo');
 const oldY=home.fisherman.y;key(83,true);await wait(200);key(83,false);check(home.fisherman.y>oldY,'Walking controls restore after sleep');
 home.fisherman.setPosition(SLEEP.outside.x,SLEEP.outside.y);
 Object.assign(scene.environment,{state:{elapsed:410,weather:'clear',remaining:160,seed:79}});
 await press();await wait(250);await press(32);await wait(1450);
 for(let i=0;i<80&&scene.sleep.active;i++)await wait(100);
 check(!scene.sleep.active&&scene.environment.phase==='morning','Space skips evening sleep and safely restores morning');
 const restored=new RiverScene(keyName);
 check(restored.environment.phase==='morning'&&restored.wallet.balance===scene.wallet.balance&&restored.equipment.levels.rod===1,'Scene reconstruction restores saved morning and progression');
 check(true,`Sleep checks complete; ${Math.round(game.loop.actualFps)} FPS`);
}catch(error){results.push(String(error));document.querySelector('#result')!.textContent=results.join('\n');}finally{key(68,false);key(83,false);}
