import Phaser from 'phaser';import {RiverScene} from '../src/game/scenes/RiverScene';import {terrainDistance,terrainField} from '../src/game/world/terrainTransitions';import {waterSpans,WORLD_WIDTH,WORLD_HEIGHT} from '../src/game/world/river';import {NETWORK_ROUTES} from '../src/game/world/regionNetwork';import {SIDE_ROUTES} from '../src/game/world/sideRoutes';
const scene=new RiverScene(null,true);const start=performance.now();new Phaser.Game({type:Phaser.AUTO,width:location.search.includes('small')?640:900,height:location.search.includes('small')?420:600,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(r=>setTimeout(r,100));scene.scene.pause();const out=document.querySelector('#result')!;out.textContent=`World ready in ${((performance.now()-start)/1000).toFixed(1)}s\n`;
const check=(v:boolean,s:string)=>{out.textContent+=(v?'PASS ':'FAIL ')+s+'\n';if(!v)throw Error(s);};
const contour=JSON.stringify(Array.from({length:WORLD_HEIGHT/2},(_,i)=>waterSpans(i*2)));const distance=terrainDistance(WORLD_WIDTH,WORLD_HEIGHT,waterSpans);check(contour===JSON.stringify(Array.from({length:WORLD_HEIGHT/2},(_,i)=>waterSpans(i*2))),'Rendering field cannot mutate collision geometry');
let samples=0;for(let y=80;y<WORLD_HEIGHT-80;y+=10)for(const[l,r]of waterSpans(y)){if(r-l<8)continue;check(distance(l+4,y)>0&&distance(r-4,y)>0,'Inside contour '+(++samples));}out.textContent=`Bake and review ready in ${((performance.now()-start)/1000).toFixed(1)}s\nPASS ${samples} shore samples agree with water collision contours\nPASS collision geometry unchanged\n`;
const texture=scene.textures.get('river'),source=texture.getSourceImage();for(let i=0;i<100;i++){scene.cameras.main.centerOn(100+i*35,500+i*40);}check(scene.textures.get('river')===texture&&texture.getSourceImage()===source,'Camera travel retains the same baked texture');
const places=[{id:'Home fork',x:2320,y:2250},{id:'Estuary island tip',x:3330,y:2400},{id:'Coast',x:3520,y:3100},...NETWORK_ROUTES.map(r=>({id:r.name,x:r.points[2]?.[0]??r.points[1][0],y:r.points[2]?.[1]??r.points[1][1]})),...SIDE_ROUTES.map(r=>({id:r.name,x:r.points[0][0],y:r.points[0][1]})),...SIDE_ROUTES.filter(r=>r.interior).map(r=>({id:r.name+' pool',x:r.pocket.x,y:r.pocket.y}))];
for(const p of places){const b=document.createElement('button');b.textContent=p.id;b.onclick=()=>{scene.cameras.main.stopFollow();scene.cameras.main.setZoom(1);scene.cameras.main.centerOn(p.x,p.y);};document.querySelector('#buttons')!.append(b);}scene.cameras.main.stopFollow();scene.cameras.main.setZoom(1);scene.cameras.main.centerOn(2320,2250);

const field=terrainField(128,128,(x)=>x<64?0:1);check(Math.abs(field(63.999,64)-field(64.001,64))<.001,'Depth shading continuous across sampling-cell joins');check(!(source as HTMLCanvasElement).getContext('2d')!.imageSmoothingEnabled,'Native pixel sampling remains unsmoothed');
// Whole-contour inspection complements the gameplay-scale camera stops.
const overview=document.createElement('canvas');overview.width=600;overview.height=800;const ov=overview.getContext('2d')!;ov.imageSmoothingEnabled=false;ov.drawImage(source as HTMLCanvasElement,0,0,600,800);document.body.append(overview);
const overviewButton=document.createElement('button');overviewButton.textContent='Whole world overview';overviewButton.onclick=()=>{document.querySelector('#test')?.setAttribute('style','display:none');out.setAttribute('style','display:none');};document.querySelector('#buttons')!.append(overviewButton);
