import Phaser from 'phaser';import {RiverScene} from '../src/game/scenes/RiverScene';import {ICE_PASSAGES,passageBounds} from '../src/game/world/traversalData';import {SaveStore} from '../src/game/player/SaveStore';import {thinIce} from '../src/game/world/driftingIce';import {waterSpans,banks} from '../src/game/world/river';
const keyName='arctic-drift.check-traversal';localStorage.removeItem(keyName);const out=document.querySelector('#result')!,check=(v:boolean,s:string)=>{out.textContent+='\n'+(v?'PASS ':'FAIL ')+s;if(!v)throw Error(s);};
const scene=new RiverScene(keyName,true);new Phaser.Game({type:Phaser.AUTO,width:1000,height:700,parent:'test',pixelArt:true,physics:{default:'arcade'},scene:[scene]});while(!scene.fishing)await new Promise(r=>setTimeout(r,100));scene.game.events.off(Phaser.Core.Events.BLUR);
const kayak=Reflect.get(scene,'kayak'),body=kayak.body as Phaser.Physics.Arcade.Body,traversal=Reflect.get(scene,'traversal'),wait=(ms:number)=>new Promise(r=>setTimeout(r,ms)),key=(down:boolean)=>window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{keyCode:83,which:83,bubbles:true}));
for(const p of ICE_PASSAGES){const b=passageBounds(p);check(waterSpans(p.y).length>1||banks(p.y)[1]-(b.x+b.width)>100||b.x-banks(p.y)[0]>100,'Main river remains open beside optional blockage: '+p.id);const permanent=scene.physics.world.staticBodies.entries.find(b=>b.left===0&&b.width>100)!;
 body.reset(b.x+b.width/2,b.y-20);key(true);await wait(100);key(false);check(traversal.sheets.some((s:any)=>s.id===p.id),'Slow contact cannot break '+p.id);
 scene.equipment.levels.speed=2;scene.equipment.levels.icebreaker=1;Reflect.set(scene.equipment,'installed',['speed','icebreaker',null]);body.reset(b.x+b.width/2,b.y-40);body.setVelocity(0,170);key(true);await wait(650);key(false);check(!traversal.sheets.some((s:any)=>s.id===p.id),'Momentum breaks '+p.id);check(permanent.gameObject.active,'Permanent land remains solid');check(!thinIce.some(s=>Math.abs(s.y-b.y)<20),'Water exclusion removed with ice');
 check(new SaveStore(keyName).load().openedPassages?.includes(p.id)===true,'Opened passage persists: '+p.id);
 const button=document.createElement('button');button.textContent=p.id;button.onclick=()=>{scene.cameras.main.stopFollow();scene.cameras.main.centerOn(b.x+b.width/2,b.y);body.reset(b.x+b.width/2,b.y+40);};document.body.prepend(button);
}
const store=new SaveStore(keyName),saved=store.load();store.write({...saved,money:73,openedPassages:undefined});check(store.load().openedPassages?.length===ICE_PASSAGES.length&&store.load().money===73,'Other save writes preserve traversal and progression');
check(true,'All passages remain open and navigable');
const {Traversal}=await import('../src/game/world/Traversal');const restored=new Traversal(scene,kayak,new SaveStore(keyName));check(Reflect.get(restored,'sheets').length===0,'Recreating traversal from saved data restores all openings');
let previewed=false;const preview=document.createElement('button');preview.textContent='Ice preview';preview.onclick=()=>{if(previewed)return;previewed=true;new Traversal(scene,kayak,new SaveStore(null));const b=passageBounds(ICE_PASSAGES[0]);body.reset(b.x+b.width/2,b.y-55);scene.cameras.main.stopFollow();scene.cameras.main.centerOn(b.x+b.width/2,b.y);};document.body.prepend(preview);
